services:
  - type: web
    name: mada-trading-bot
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TRADING_MODE
        value: DEMO
      - key: PORT
        value: 10000
